version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Kiev
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.5.0
