language: php

sudo: false

php:
  - 5.6
  - 7.0

before_script:
  - composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpcs --standard=PSR2 src/
  - ./vendor/bin/phpunit

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true
